In [1]:
import asyncio
import nest_asyncio
nest_asyncio.apply()

In [2]:
import asyncio
from playwright.async_api import async_playwright

async def test_browser():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.goto('https://example.com')
        print(f'Title: {await page.title()}')
        await browser.close()

asyncio.run(test_browser())

Title: Example Domain

In [4]:
import asyncio
from crawl4ai import AsyncWebCrawler, CrawlerRunConfig
from crawl4ai.content_scraping_strategy import LXMLWebScrapingStrategy
from crawl4ai.deep_crawling import BestFirstCrawlingStrategy
from crawl4ai.deep_crawling.filters import (
    FilterChain,
    DomainFilter,
    URLPatternFilter,
    ContentTypeFilter
)
from crawl4ai.deep_crawling.scorers import KeywordRelevanceScorer
from typing import List
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator

async def run_advanced_crawler(base_url:str,url_patterns:List[str]):
    # Create a sophisticated filter chain
    filter_chain = FilterChain([
        # URL patterns to include
        URLPatternFilter(patterns=url_patterns),
    ])

    # Set up the configuration
    config = CrawlerRunConfig(
        deep_crawl_strategy=BestFirstCrawlingStrategy(
            max_depth=2,
            include_external=False,
            filter_chain=filter_chain,
        ),
         # Content thresholds
        word_count_threshold=10,        # Minimum words per block

        # Tag exclusions
        excluded_tags=['form','footer', 'nav'],
        css_selector="#content-area",  # Only extract main content
        exclude_all_images=True,
        scraping_strategy=LXMLWebScrapingStrategy(),
        stream=True,
        verbose=True,
        markdown_generator=DefaultMarkdownGenerator(),
    )

    # Execute the crawl
    results = []
    async with AsyncWebCrawler() as crawler:
        async for result in await crawler.arun(url=base_url, config=config):
            results.append(result)
            score = result.metadata.get("score", 0)
            depth = result.metadata.get("depth", 0)
            print(f"Depth: {depth} | Score: {score:.2f} | {result.url}")

    # Analyze the results
    print(f"Crawled {len(results)} high-value pages")
    print(f"Average score: {sum(r.metadata.get('score', 0) for r in results) / len(results):.2f}")

    # Group by depth
    depth_counts = {}
    for result in results:
        depth = result.metadata.get("depth", 0)
        depth_counts[depth] = depth_counts.get(depth, 0) + 1

    print("Pages crawled by depth:")
    for depth, count in sorted(depth_counts.items()):
        print(f"  Depth {depth}: {count} pages")

    return results 

base_url = "https://docs.prefect.io/v3"
url_patterns = ["*tutorials*","*develop*","*deploy*","*automate*","*manage*","*migrate*"]
# url_patterns = ["*tutorials*"]
# keywords = ["tutorials"]
results = asyncio.run(run_advanced_crawler(base_url=base_url,url_patterns=url_patterns))

[INIT].... → Crawl4AI 0.6.3

[FETCH]... ↓ https://docs.prefect.io/v3                                                                           |
✓ | ⏱: 1.66s

[SCRAPE].. ◆ https://docs.prefect.io/v3                                                                           |
✓ | ⏱: 0.01s

[COMPLETE] ● https://docs.prefect.io/v3                                                                           |
✓ | ⏱: 1.68s

Depth: 0 | Score: 0.00 | https://docs.prefect.io/v3

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/configuration/manage-settings                               |
✓ | ⏱: 1.16s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/configuration/manage-settings                               |
✓ | ⏱: 0.01s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/configuration/manage-settings                               |
✓ | ⏱: 1.18s

Depth: 1 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/configuration/manage-settings

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/deployment_infra/managed                                    |
✓ | ⏱: 3.07s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/deployment_infra/managed                                    |
✓ | ⏱: 0.08s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/deployment_infra/managed                                    |
✓ | ⏱: 3.17s

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/deployments/create-deployments                              |
✓ | ⏱: 3.16s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/deployments/create-deployments                              |
✓ | ⏱: 0.03s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/deployments/create-deployments                              |
✓ | ⏱: 3.21s

Depth: 1 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/deployment_infra/managed
Depth: 1 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/deployments/create-deployments

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-to-prefect-3                                |
✓ | ⏱: 3.22s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-to-prefect-3                                |
✓ | ⏱: 0.33s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-to-prefect-3                                |
✓ | ⏱: 3.57s

Depth: 1 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-to-prefect-3

[FETCH]... ↓ https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-ci-cd                               |
✓ | ⏱: 15.34s

[SCRAPE].. ◆ https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-ci-cd                               |
✓ | ⏱: 0.10s

[COMPLETE] ● https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-ci-cd                               |
✓ | ⏱: 15.47s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-ci-cd

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/cloud/manage-users/api-keys                                 |
✓ | ⏱: 12.25s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/cloud/manage-users/api-keys                                 |
✓ | ⏱: 0.27s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/cloud/manage-users/api-keys                                 |
✓ | ⏱: 12.66s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/cloud/manage-users/api-keys

[FETCH]... ↓ https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-via-python                          |
✓ | ⏱: 16.02s

[SCRAPE].. ◆ https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-via-python                          |
✓ | ⏱: 1.42s

[COMPLETE] ● https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-via-python                          |
✓ | ⏱: 17.56s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-via-python

[FETCH]... ↓ https://docs.prefect.io/v3/deploy/infrastructure-concepts/work-pools                                 |
✓ | ⏱: 14.99s

[SCRAPE].. ◆ https://docs.prefect.io/v3/deploy/infrastructure-concepts/work-pools                                 |
✓ | ⏱: 0.19s

[COMPLETE] ● https://docs.prefect.io/v3/deploy/infrastructure-concepts/work-pools                                 |
✓ | ⏱: 15.23s

[FETCH]... ↓ https://docs.prefect.io/v3/deploy/infrastructure-concepts/prefect-yaml                               |
✓ | ⏱: 15.12s

[SCRAPE].. ◆ https://docs.prefect.io/v3/deploy/infrastructure-concepts/prefect-yaml                               |
✓ | ⏱: 0.25s

[COMPLETE] ● https://docs.prefect.io/v3/deploy/infrastructure-concepts/prefect-yaml                               |
✓ | ⏱: 15.38s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/deploy/infrastructure-concepts/prefect-yaml
Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/deploy/infrastructure-concepts/work-pools

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/deployment_infra/run-flows-in-local-processes               |
✓ | ⏱: 6.41s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/deployment_infra/run-flows-in-local-processes               |
✓ | ⏱: 0.15s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/deployment_infra/run-flows-in-local-processes               |
✓ | ⏱: 6.59s

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/deployment_infra/serverless                                 |
✓ | ⏱: 6.58s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/deployment_infra/serverless                                 |
✓ | ⏱: 0.08s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/deployment_infra/serverless                                 |
✓ | ⏱: 6.66s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/deployment_infra/serverless
Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/deployment_infra/run-flows-in-local-processes

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/deployment_infra/docker                                     |
✓ | ⏱: 6.61s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/deployment_infra/docker                                     |
✓ | ⏱: 0.07s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/deployment_infra/docker                                     |
✓ | ⏱: 6.69s

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/deployments/run-deployments                                 |
✓ | ⏱: 8.52s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/deployments/run-deployments                                 |
✓ | ⏱: 0.03s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/deployments/run-deployments                                 |
✓ | ⏱: 8.56s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/deployment_infra/docker
Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/deployments/run-deployments

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/migrate/airflow                                             |
✓ | ⏱: 1.34s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/migrate/airflow                                             |
✓ | ⏱: 0.07s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/migrate/airflow                                             |
✓ | ⏱: 1.42s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/migrate/airflow

[FETCH]... ↓ https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-agents-to-workers                           |
✓ | ⏱: 1.21s

[SCRAPE].. ◆ https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-agents-to-workers                           |
✓ | ⏱: 0.04s

[COMPLETE] ● https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-agents-to-workers                           |
✓ | ⏱: 1.26s

Depth: 2 | Score: 0.00 | https://docs.prefect.io/v3/how-to-guides/migrate/upgrade-agents-to-workers
Crawled 16 high-value pages
Average score: 0.00
Pages crawled by depth:
  Depth 0: 1 pages
  Depth 1: 4 pages
  Depth 2: 11 pages

In [5]:
markdowns = [result.markdown for result in results]

In [6]:
with open("prefect_v3_docs.md","w") as f:
    f.writelines(markdowns)

In [17]:
import pandas as pd

data = [{"id":1,"image_ok":True,"text":"abcde dgh"},{"id":1,"image_ok":True,"text":"abcde#dgh"},{"id":1,"image_ok":True,"text":"abcde#dklmgh"}]

In [18]:
df = pd.DataFrame(data=data)

import re
def normalize(text):
    text = re.sub(r"\s+"," ",text)
    return re.sub(r"([^A-Za-z0-9]+)","",text)

df["text"] = df["text"].apply(normalize)

In [19]:
df

   id  image_ok         text
0   1      True     abcdedgh
1   1      True     abcdedgh
2   1      True  abcdedklmgh

In [ ]:
df = df[(df["image_ok"]==True) & (df["text"]!="") ]
df

   id  image_ok         text
0   1      True     abcdedgh
2   1      True  abcdedklmgh

In [21]:
df = df.drop_duplicates(subset=["text"])
df

   id  image_ok         text
0   1      True     abcdedgh
2   1      True  abcdedklmgh